import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Feature from './components/feature';
import Subscribe from './components/subscribe';
import SimpleForm from './components/SimpleForm';
import BlogComponent from './components/blogComponent';
import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
 
  const router=useRouter();
  const handleClick=()=>{
    router.push('/blogWriting')
  }
  return (
    
    <div className={styles.container}>
      <Head>
        <title>abha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
     <div className={styles.home_title_section}>
      <div className={styles.title_left_section}>
       <h1>Spicy Blog Hunter</h1>
       <p>
       Welcome to <span style={{fontSize:"2rem", color:"ActiveBorder"}}>Spicy Blog Hunter</span>,
        a platform where words come to life and ideas find their voice. Explore a diverse range of topics, from lifestyle and technology to travel and beyond, curated by passionate writers from around the world.
       </p>
       <button onClick={handleClick}>Create Your Blog</button>
      
            </div>
    
     </div>
     <div className={styles.home_second}>
      <div className={styles.home_second_left}>
      <h1>Learn How to Get Anything You Want
</h1>
<p>Listen to this FREE audio from Marie and learn the <span style={{color:"gray",fontSize:"1.6rem"}}>3 steps that will change your life, fast.</span></p>
  <SimpleForm/>
  <p>By entering your info, you’ll become an MF Insider – with FREE access to exclusive insights, private Q+As, and inspiring episodes of MarieTV, delivered with 💜 to your inbox. (Unsub anytime in a click.) You also agree to our Terms of Use and Privacy Policy.</p>
      </div>
      <div className={styles.home_second_right}>
     <img src='https://i.pinimg.com/originals/70/0b/7f/700b7f59d4386aa731eb53d03c2f94e5.jpg'/>
     <img src='https://i.pinimg.com/originals/08/08/38/080838344450f717569850f4913a9485.jpg'/>
     <img src='https://i.pinimg.com/736x/a1/1d/c0/a11dc04d8895a4e1e2b82803aca21f13.jpg'/>
   </div>
      
     </div>
     <div className={styles.home_third}>
     <div className={styles.home_third_left}>
     <h3>Abha!</h3>
     <h1>I M ABHA</h1>
     <p>My hunch is someone you trust mentioned my name, or you stumbled upon one of my videos, quotes or articles online. Whatever path you took, I’m really glad you’re here. This site is full of incredible resources and ideas that can help you change your life
       (not kidding!). Here’s a quick lay of the land so you can find what you’re looking for and we can start something beautiful together.</p>
     <button>LEARN MORE</button>
     </div>
     <div className={styles.home_third_right}>
   <img src='https://freepngimg.com/save/16672-model-png-clipart/636x638'/>
     </div>
      </div>
     <Feature/>
     <Subscribe/>
    </div>

  )
}
